### ISSUE TITLE
verify CI builds and publishes docker image to ghcr.io/fprime-community/fprime-workspace-image

### ISSUE THREAD

**Issue by capsulecorplab** [fprime-community/fprime-workspace-image#47]
follow-up to #33

**Comment by capsulecorplab** [comment]
@thomas-bc sorry to bug you again, but it seems ghcr needs to be enabled for the fprime-community. Otherwise, the CI pipeline needed to publish images is broken https://github.com/fprime-community/fprime-workspace-image/actions/runs/7404465060/job/20146022620#step:6:328

**Comment by capsulecorplab** [comment]
> They seem to be enabled already... I'm assuming the token in the repository secrets is yours? I wonder if maybe that could be it - I'll try to replace it with another token. Sorry for the delay, I've been busy with other things. I'll get back to this as soon as I can

No worries. Yeah, I generated the personal access token and added it as a repo secret; that could likely be the issue... If it helps, here are my notes on how I set up GHCR for my other Kasm workspaces https://gist.github.com/capsulecorplab/75b930c42188006ed56a3785aa797971

**Comment by thomas-bc** [comment]
@capsulecorplab some updates:
- I added valid credentials and was able to re-run the action that successfully pushed to `ghcr.io/fprime-community/...` 🎉 
- I figured it out too late, but I was able to grant permissions on the package registry to mimic those on the repository, could you please try to update the secret in the repository and see if that works?
- package should be published under the package section of the repository. let me know if that's all good?

Question, what makes the image so large? Seems the base image is only a couple hundred MB, where this is in the order of ~10GB ?

**Comment by capsulecorplab** [comment]
Thanks, @thomas-bc ! Closing this issue as per the fantastic updates from #49!

As for the image size, I suspect the Arduino board package index could be contributing to a good portion of the image space, as I've also witnessed the same happen in one of my other [IIaC workspaces](https://github.com/tetrabiodistributed/tetra-workspace-image). Though, not entirely sure why it's in the order of ~10GB

**Comment by capsulecorplab** [comment]
Opened #51 as a reminder to investigate the disk space usage
